{{- if .Values.puppetserver.puppeturl }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: r10k-code-config
  labels:
    {{- include "puppetserver.r10k.labels" . | nindent 4 }}
data:
  r10k.yaml: |
    # The location to use for storing cached Git repos
    :cachedir: '/etc/puppetlabs/code/r10k_cache'
    # A list of git repositories to create
    :sources:
      # This will clone the git repository and instantiate an environment per
      # branch in '/etc/puppetlabs/code/environments'
      :puppet_repo:
        remote: '{{.Values.puppetserver.puppeturl}}'
        basedir: '/etc/puppetlabs/code/environments'
    :git:
      provider: 'rugged' # Either 'shellgit' or 'rugged', defaults to 'shellgit'
    {{- with .Values.r10k.code.viaSsh.credentials }}
    {{- if or (.existingSecret) (and (.ssh.value) (.known_hosts.value)) }}
      private_key: '/home/puppet/.ssh/id_rsa'
    {{- end }}
    {{- end }}
      repositories:
        - remote: '{{.Values.puppetserver.puppeturl}}'
{{- end }}
