{{- if .Values.puppetserver.puppeturl }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: r10k-code-config
  labels:
    {{- include "puppetserver.r10k.labels" . | nindent 4 }}
data:
  r10k.yaml: |
    # The location to use for storing cached Git repos
    :cachedir: '/etc/puppetlabs/code/r10k_cache'
    # A list of git repositories to create
    :sources:
      # This will clone the git repository and instantiate an environment per
      # branch in '/etc/puppetlabs/code/environments'
      :puppet_repo:
        remote: '{{.Values.puppetserver.puppeturl}}'
        basedir: '/etc/puppetlabs/code/environments'

  r10k.cronjob.sh: |
    #!/bin/sh

    # not needed anymore, as crond handels this - .startingDeadlineSeconds: {{ .startingDeadlineSeconds }}
    # not needed anymore, as crond handels this - .activeDeadlineSeconds: {{ .activeDeadlineSeconds }}

    {{- if .Values.r10k.code.cronJob.concurrencyPolicy }}
      {{- if eq .Values.r10k.code.cronJob.concurrencyPolicy "Forbid" }}
        if [ -e /run/r10k.cronjob.pid ] && pgrep $(</run/r10k.cronjob.pid); then
          exit 0
        fi
      {{- else if eq .Values.r10k.code.cronJob.concurrencyPolicy "Replace" }}
        if [ -e /run/r10k.cronjob.pid ]; then
          pkill $(</run/r10k.cronjob.pid)
        fi
      {{- end }}
    {{- end }}

    echo $PPID > /run/r10k.cronjob.pid

    # extra_args="{{ .Values.r10k.code.extraArgs }}"  # parsing yaml-maps to bash?
    /docker-entrypoint.sh deploy environment --config /etc/puppetlabs/puppet/r10k.yaml --puppetfile

    echo $?

    rm /run/r10k.cronjob.pid

    {{- if .Values.r10k.code.cronJob.restartPolicy }}
      {{- if eq .Values.r10k.code.cronJob.restartPolicy "OnFailure" }}
        if (( $? != 0 )); then
          /bin/sh -c /r10k.cronjob.sh
        fi
      {{- else if eq .Values.r10k.code.cronJob.restartPolicy "Never" }}
        # Never restart? No, this is a cron sidecar, we want this to run forever
      {{- else if eq .Values.r10k.code.cronJob.restartPolicy "Always" }}
        # Always restart? Yes, this is a cron sidecar, we want this to run forever
      {{- end }}
    {{- end }}

  r10k.entrypoint.sh: |
    #!/bin/sh

    apk add --update busybox-suid
    touch /tmp/script.log

    /usr/bin/crontab - <<'EOF'
      {{ .Values.r10k.code.cronJob.schedule }} /bin/sh -c /opt/r10k.cronjob.sh >> /var/log/script.log
    EOF

    crond
    tail -f /tmp/script.log

{{- end }}
